name: Watch Tickets

on:
  schedule:
    # 03:00 UTC = 12:00 JST 毎日実行
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run watcher
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          QUERY: ${{ vars.QUERY }}
          NOTIFY_ALWAYS: ${{ vars.NOTIFY_ALWAYS }}
          SLACK_MENTION: ${{ vars.SLACK_MENTION }}
        run: |
          npm run start
